const MODULO_PEDIDOS = '/frmpedido';
const MODULO_PRESUPUESTO = '/presupuesto';
const MODULO_ORDENES_DE_COMPRA = '/orden_compra';
const MODULO_COMPRAS = '/compras';
const MODULO_NCC = '/nota_credito_compras';
const MODULO_NDC = '/nota_debito_compra';
const MODULO_NRC = '/nota_remision_compra';
const MODULO_LIBROCOMPRAS = '/obtener_libro_compras';


const MODULO_PRODUCCION_ORDEN_COMPRA_LOTE = 'orden_compra_lote';
const MODULO_PRODUCCION_COMPRA_LORE = '/compra_lote';
const MODULO_PRODUCCION_URBANIZACION = '/urbanizacion';
const MODULO_PRODUCCION_PRECIO = '/precio';
const MODULO_PRODUCCION_CONTRATO = '/contrato';
const MODULO_PRODUCCION_RESCISION = '/resccontrato';
const MODULO_PRODUCCION_CESION = '/cesion_derecho';

const MODULO_APERTURA_CAJA = '/AperturaCaja';
const MODULO_CIERRE_CAJA = '/CierreCaja';
const MODULO_VENTA = '/venta_cuenta_cobrar';
const MODULO_COBRANZA = '/cobranza';
const MODULO_NRV = '/nota_remision_venta';
const MODULO_NCV = '/nota_credito_venta';
const MODULO_NDV = '/nota_debito_venta';
const MODULO_ARQUEO = '/arqueo_caja';
const MODULO_LIBRO_VENTA = '/obtener_libro_venta';


const MODULO_MANTENIMIENTO_BARRIO = '/frmbarrio';
const MODULO_MANTENIMIENTO_CAJA = '/frmcaja';
const MODULO_MANTENIMIENTO_CATEGORIA = '/frmcategoria';
const MODULO_MANTENIMIENTO_CIUDAD = '/frmciudad';
const MODULO_MANTENIMIENTO_CLIENTE = '/cliente';
const MODULO_MANTENIMIENTO_EFECTIVO = '/efectivo';
const MODULO_MANTENIMIENTO_FORMA_COBRO = '/forma_cobro';
const MODULO_MANTENIMIENTO_FUNCIONARIO = '/funcionario';
const MODULO_MANTENIMIENTO_IVA = '/frmiva';
const MODULO_MANTENIMIENTO_MANZANA = '/manzana';
const MODULO_MANTENIMIENTO_MARCA = '/frmmarca';
const MODULO_MANTENIMIENTO_MONEDA = '/moneda';
const MODULO_MANTENIMIENTO_MOTIVO_CESION = '/motivo_cesion_derecho_deuda';
const MODULO_MANTENIMIENTO_MOTIVO_RESCISION = '/motivo_rescision_contrato';
const MODULO_MANTENIMIENTO_MOTIVO_TRASLADO = '/motivo_traslado_remision';
const MODULO_MANTENIMIENTO_NIVEL = '/nivel';
const MODULO_MANTENIMIENTO_NUMERO_ESTABLECIMIENTO = '/frmnumero_establecimiento';
const MODULO_MANTENIMIENTO_NUMERO_EXPEDICION = '/frmnumero_expedicion';
const MODULO_MANTENIMIENTO_PRODUCTO = '/producto';
const MODULO_MANTENIMIENTO_PROVEEDOR = '/proveedor';
const MODULO_MANTENIMIENTO_SUCURSAL = '/frmsucursal';
const MODULO_MANTENIMIENTO_TIPO_DOCUMENTO = '/frmtipo_documento';
const MODULO_MANTENIMIENTO_TIPO_VENTA = '/tipoventa';
const MODULO_MANTENIMIENTO_TIPO_PRODUCTO = '/tipo_producto';
const MODULO_MANTENIMIENTO_TIMBRADO = '/timbrado';
const MODULO_MANTENIMIENTO_USUARIO = '/frmusuario';



const PERMISO_POR_NIVEL = {
    1: [MODULO_PEDIDOS, MODULO_PRESUPUESTO, MODULO_ORDENES_DE_COMPRA,
        MODULO_COMPRAS, MODULO_NCC, MODULO_NDC, MODULO_NRC, MODULO_LIBROCOMPRAS],
    2: [MODULO_COMPRAS, MODULO_ORDENES_DE_COMPRA, MODULO_PRESUPUESTO],

    3: [MODULO_PRODUCCION_ORDEN_COMPRA_LOTE, MODULO_PRODUCCION_COMPRA_LORE, MODULO_PRODUCCION_URBANIZACION,
        MODULO_PRODUCCION_PRECIO, MODULO_PRODUCCION_CONTRATO, MODULO_PRODUCCION_RESCISION,
        MODULO_PRODUCCION_CESION],
    4: [MODULO_PRODUCCION_ORDEN_COMPRA_LOTE, MODULO_PRODUCCION_COMPRA_LORE, MODULO_PRODUCCION_URBANIZACION,
        MODULO_PRODUCCION_PRECIO],


    5: [MODULO_APERTURA_CAJA, MODULO_CIERRE_CAJA, MODULO_VENTA,
        MODULO_COBRANZA, MODULO_NRV, MODULO_NCV, MODULO_NDV,
        MODULO_ARQUEO, MODULO_LIBRO_VENTA],
    6: [MODULO_APERTURA_CAJA, MODULO_CIERRE_CAJA],


    7: [MODULO_MANTENIMIENTO_BARRIO, MODULO_MANTENIMIENTO_CAJA, MODULO_MANTENIMIENTO_CATEGORIA,
        MODULO_MANTENIMIENTO_CIUDAD, MODULO_MANTENIMIENTO_CLIENTE, MODULO_MANTENIMIENTO_EFECTIVO,
        MODULO_MANTENIMIENTO_FORMA_COBRO, MODULO_MANTENIMIENTO_FUNCIONARIO, MODULO_MANTENIMIENTO_IVA,
        MODULO_MANTENIMIENTO_MANZANA, MODULO_MANTENIMIENTO_MARCA, MODULO_MANTENIMIENTO_MONEDA,
        MODULO_MANTENIMIENTO_MOTIVO_CESION, MODULO_MANTENIMIENTO_MOTIVO_RESCISION,
        MODULO_MANTENIMIENTO_MOTIVO_TRASLADO, MODULO_MANTENIMIENTO_NIVEL,
        MODULO_MANTENIMIENTO_NUMERO_ESTABLECIMIENTO, MODULO_MANTENIMIENTO_NUMERO_EXPEDICION,
        MODULO_MANTENIMIENTO_PRODUCTO, MODULO_MANTENIMIENTO_PROVEEDOR, MODULO_MANTENIMIENTO_SUCURSAL,
        MODULO_MANTENIMIENTO_TIPO_DOCUMENTO, MODULO_MANTENIMIENTO_TIPO_VENTA,
        MODULO_MANTENIMIENTO_TIPO_PRODUCTO, MODULO_MANTENIMIENTO_TIMBRADO, MODULO_MANTENIMIENTO_USUARIO],


    8: [MODULO_PEDIDOS, MODULO_PRESUPUESTO, MODULO_ORDENES_DE_COMPRA,
        MODULO_COMPRAS, MODULO_NCC, MODULO_NDC, MODULO_NRC, MODULO_LIBROCOMPRAS, MODULO_PRODUCCION_ORDEN_COMPRA_LOTE,
        MODULO_PRODUCCION_COMPRA_LORE, MODULO_PRODUCCION_URBANIZACION,
        MODULO_PRODUCCION_PRECIO, MODULO_PRODUCCION_CONTRATO, MODULO_PRODUCCION_RESCISION,
        MODULO_PRODUCCION_CESION, MODULO_APERTURA_CAJA, MODULO_CIERRE_CAJA, MODULO_VENTA,
        MODULO_COBRANZA, MODULO_NRV, MODULO_NCV, MODULO_NDV,
        MODULO_ARQUEO, MODULO_LIBRO_VENTA, MODULO_MANTENIMIENTO_BARRIO, MODULO_MANTENIMIENTO_CAJA, MODULO_MANTENIMIENTO_CATEGORIA,
        MODULO_MANTENIMIENTO_CIUDAD, MODULO_MANTENIMIENTO_CLIENTE, MODULO_MANTENIMIENTO_EFECTIVO,
        MODULO_MANTENIMIENTO_FORMA_COBRO, MODULO_MANTENIMIENTO_FUNCIONARIO, MODULO_MANTENIMIENTO_IVA,
        MODULO_MANTENIMIENTO_MANZANA, MODULO_MANTENIMIENTO_MARCA, MODULO_MANTENIMIENTO_MONEDA,
        MODULO_MANTENIMIENTO_MOTIVO_CESION, MODULO_MANTENIMIENTO_MOTIVO_RESCISION,
        MODULO_MANTENIMIENTO_MOTIVO_TRASLADO, MODULO_MANTENIMIENTO_NIVEL,
        MODULO_MANTENIMIENTO_NUMERO_ESTABLECIMIENTO, MODULO_MANTENIMIENTO_NUMERO_EXPEDICION,
        MODULO_MANTENIMIENTO_PRODUCTO, MODULO_MANTENIMIENTO_PROVEEDOR, MODULO_MANTENIMIENTO_SUCURSAL,
        MODULO_MANTENIMIENTO_TIPO_DOCUMENTO, MODULO_MANTENIMIENTO_TIPO_VENTA,
        MODULO_MANTENIMIENTO_TIPO_PRODUCTO, MODULO_MANTENIMIENTO_TIMBRADO, MODULO_MANTENIMIENTO_USUARIO]
}
export { PERMISO_POR_NIVEL }