const MODULO_PEDIDOS = '/frmpedido';
const MODULO_PRESUPUESTO = '/presupuesto';
const MODULO_ORDENES_DE_COMPRA = '/orden_compra';
const MODULO_COMPRAS = '/compras';
const MODULO_NCC = '/nota_credito_compras';
const MODULO_NDC = '/nota_debito_compra';
const MODULO_NRC = '/nota_remision_compra';
const MODULO_LIBROCOMPRAS = '/obtener_libro_compras';


const MODULO_PRODUCCION_ORDEN_COMPRA_LOTE = 'orden_compra_lote';
const MODULO_PRODUCCION_COMPRA_LORE = '/compra_lote';
const MODULO_PRODUCCION_URBANIZACION = '/urbanizacion';
const MODULO_PRODUCCION_PRECIO = '/precio';
const MODULO_PRODUCCION_CONTRATO = '/contrato';
const MODULO_PRODUCCION_RESCISION = '/resccontrato';
const MODULO_PRODUCCION_CESION = '/cesion_derecho';

const MODULO_APERTURA_CAJA = '/AperturaCaja';
const MODULO_CIERRE_CAJA = '/CierreCaja';
const MODULO_VENTA = '/venta_cuenta_cobrar';
const MODULO_COBRANZA = '/cobranza';
const MODULO_NRV = '/nota_remision_venta';
const MODULO_NCV = '/nota_credito_venta';
const MODULO_NDV = '/nota_debito_venta';
const MODULO_ARQUEO = '/arqueo_caja';
const MODULO_LIBRO_VENTA = '/obtener_libro_venta';


const MODULO_MANTENIMIENTO_BARRIO = '/frmbarrio';
const MODULO_MANTENIMIENTO_CAJA = '/frmcaja';
const MODULO_MANTENIMIENTO_CATEGORIA = '/frmcategoria';
const MODULO_MANTENIMIENTO_CIUDAD = '/frmciudad';
const MODULO_MANTENIMIENTO_CLIENTE = '/cliente';
const MODULO_MANTENIMIENTO_EFECTIVO = '/efectivo';
const MODULO_MANTENIMIENTO_FORMA_COBRO = '/forma_cobro';
const MODULO_MANTENIMIENTO_FUNCIONARIO = '/funcionario';
const MODULO_MANTENIMIENTO_IVA = '/frmiva';
const MODULO_MANTENIMIENTO_MANZANA = '/manzana';
const MODULO_MANTENIMIENTO_MARCA = '/frmmarca';
const MODULO_MANTENIMIENTO_MONEDA = '/moneda';
const MODULO_MANTENIMIENTO_MOTIVO_CESION = '/motivo_cesion_derecho_deuda';
const MODULO_MANTENIMIENTO_MOTIVO_RESCISION = '/motivo_rescision_contrato';
const MODULO_MANTENIMIENTO_MOTIVO_TRASLADO = '/motivo_traslado_remision';
const MODULO_MANTENIMIENTO_NIVEL = '/nivel';
const MODULO_MANTENIMIENTO_NUMERO_ESTABLECIMIENTO = '/frmnumero_establecimiento';
const MODULO_MANTENIMIENTO_NUMERO_EXPEDICION = '/frmnumero_expedicion';
const MODULO_MANTENIMIENTO_PRODUCTO = '/producto';
const MODULO_MANTENIMIENTO_PROVEEDOR = '/proveedor';
const MODULO_MANTENIMIENTO_SUCURSAL = '/frmsucursal';
const MODULO_MANTENIMIENTO_TIPO_DOCUMENTO = '/frmtipo_documento';
const MODULO_MANTENIMIENTO_TIPO_VENTA = '/tipoventa';
const MODULO_MANTENIMIENTO_TIPO_PRODUCTO = '/tipo_producto';
const MODULO_MANTENIMIENTO_TIMBRADO = '/timbrado';
const MODULO_MANTENIMIENTO_USUARIO = '/frmusuario';
const MODULO_MANTENIMIENTO_COPIA_SEGURIDAD = '/copia_seguridad';




const MODULO_INFORMES_PEDIDO = '/informe_compras/informe_pedido.vue';
const MODULO_INFORMES_ORDEN_COMPRA = '/informe_compras/informe_orden_compra.vue';
const MODULO_INFORMES_PRESUPUESTO = '/informe_compras/informe_presupuesto.vue';
const MODULO_INFORMES_COMPRA = '/informe_compras/informe_compra.vue';
const MODULO_INFORMES_NOTA_CREDITO_COMPRA = '/informe_compras/informe_nota_credito_compra.vue';
const MODULO_INFORMES_NOTA_DEBITO_COMPRA = '/informe_compras/informe_nota_debito_compra.vue';
const MODULO_INFORMES_NOTA_REMISION_COMPRA = '/informe_compras/informe_nota_remision_compra.vue';


const MODULO_INFORMES_BARRIO = '/informe_mantenimiento/informe_barrio.vue';
const MODULO_INFORMES_CAJA = '/informe_mantenimiento/informe_caja.vue';
const MODULO_INFORMES_CIUDAD = '/informe_mantenimiento/informe_ciudad.vue';
const MODULO_INFORMES_CATEGORIA = '/informe_mantenimiento/informe_categoria.vue';
const MODULO_INFORMES_CLIENTE = '/informe_mantenimiento/informe_cliente.vue';
const MODULO_INFORMES_EFECTIVO = '/informe_mantenimiento/informe_efectivo.vue';
const MODULO_INFORMES_FORMA_COBRO = '/informe_mantenimiento/informe_forma_cobro.vue';
const MODULO_INFORMES_FUNCIONARIO = '/informe_mantenimiento/informe_funcionario.vue';
const MODULO_INFORMES_IVA = '/informe_mantenimiento/informe_iva.vue';
const MODULO_INFORMES_MANZANA = '/informe_mantenimiento/informe_manzana.vue';
const MODULO_INFORMES_MARCA = '/informe_mantenimiento/informe_marca.vue';
const MODULO_INFORMES_MONEDA = '/informe_mantenimiento/informe_moneda.vue';
const MODULO_INFORMES_MOTIVO_CESION = '/informe_mantenimiento/informe_motivo_cesion_contrato.vue';
const MODULO_INFORMES_MOTIVO_RESCISION = '/informe_mantenimiento/informe_motivo_rescision_contrato.vue';
const MODULO_INFORMES_MOTIVO_TRASLADO = '/informe_mantenimiento/informe_motivo_traslado.vue';
const MODULO_INFORMES_NIVEL = '/informe_mantenimiento/informe_nivel.vue';
const MODULO_INFORMES_NUMERO_ESTABLECIMIENTO = '/informe_mantenimiento/informe_numero_establecimiento.vue';
const MODULO_INFORMES_NUMERO_EXPEDICION = '/informe_mantenimiento/informe_numero_expedicion.vue';
const MODULO_INFORMES_PRODUCTO = '/informe_mantenimiento/informe_producto.vue';
const MODULO_INFORMES_PROVEEDOR = '/informe_mantenimiento/informe_proveedor.vue';
const MODULO_INFORMES_SUCURSAL = '/informe_mantenimiento/informe_sucursal.vue';
const MODULO_INFORMES_TIPO_DOCUMENTO = '/informe_mantenimiento/informe_tipo_documento.vue';
const MODULO_INFORMES_TIPO_VENTA = '/informe_mantenimiento/informe_tipo_producto.vue';
const MODULO_INFORMES_TIPO_PRODUCTO = '/informe_mantenimiento/informe_tipo_venta.vue';
const MODULO_INFORMES_TIMBRADO = '/informe_mantenimiento/informe_timbrado.vue';
const MODULO_INFORMES_USUARIO = '/informe_mantenimiento/informe_usuario.vue';


const MODULO_INFORMES_ORDEN_COMPRA_LOTE = '/informe_produccion/informe_orden_compra_lote.vue';
const MODULO_INFORMES_COMPRA_LOTE = '/informe_produccion/informe_compra_lote.vue';
const MODULO_INFORMES_URBANIZACION = '/informe_produccion/informe_urbanizacion.vue';
const MODULO_INFORMES_CONTRATO = '/informe_produccion/informe_contrato.vue';
const MODULO_INFORMES_VENTA = '/informe_ventas/informe_venta.vue';
const MODULO_INFORMES_NOTA_CREDITO_VENTA = '/informe_ventas/informe_nota_credito_venta.vue';
const MODULO_INFORMES_NOTA_DEBITO_VENTA = '/informe_ventas/informe_nota_debito_venta.vue';
const MODULO_INFORMES_NOTA_REMISION_VENTA = '/informe_ventas/informe_nota_remision_venta.vue';





const PERMISO_POR_NIVEL = {
    1: [MODULO_PEDIDOS, MODULO_PRESUPUESTO, MODULO_ORDENES_DE_COMPRA,
        MODULO_COMPRAS, MODULO_NCC, MODULO_NDC, MODULO_NRC, MODULO_LIBROCOMPRAS],
    2: [MODULO_COMPRAS, MODULO_ORDENES_DE_COMPRA, MODULO_PRESUPUESTO],

    3: [MODULO_PRODUCCION_ORDEN_COMPRA_LOTE, MODULO_PRODUCCION_COMPRA_LORE, MODULO_PRODUCCION_URBANIZACION,
        MODULO_PRODUCCION_PRECIO, MODULO_PRODUCCION_CONTRATO, MODULO_PRODUCCION_RESCISION,
        MODULO_PRODUCCION_CESION],
    4: [MODULO_PRODUCCION_ORDEN_COMPRA_LOTE, MODULO_PRODUCCION_COMPRA_LORE, MODULO_PRODUCCION_URBANIZACION,
        MODULO_PRODUCCION_PRECIO],


    5: [MODULO_APERTURA_CAJA, MODULO_CIERRE_CAJA, MODULO_VENTA,
        MODULO_COBRANZA, MODULO_NRV, MODULO_NCV, MODULO_NDV,
        MODULO_ARQUEO, MODULO_LIBRO_VENTA],
    6: [MODULO_APERTURA_CAJA, MODULO_CIERRE_CAJA],


    7: [MODULO_MANTENIMIENTO_BARRIO, MODULO_MANTENIMIENTO_CAJA, MODULO_MANTENIMIENTO_CATEGORIA,
        MODULO_MANTENIMIENTO_CIUDAD, MODULO_MANTENIMIENTO_CLIENTE, MODULO_MANTENIMIENTO_EFECTIVO,
        MODULO_MANTENIMIENTO_FORMA_COBRO, MODULO_MANTENIMIENTO_FUNCIONARIO, MODULO_MANTENIMIENTO_IVA,
        MODULO_MANTENIMIENTO_MANZANA, MODULO_MANTENIMIENTO_MARCA, MODULO_MANTENIMIENTO_MONEDA,
        MODULO_MANTENIMIENTO_MOTIVO_CESION, MODULO_MANTENIMIENTO_MOTIVO_RESCISION,
        MODULO_MANTENIMIENTO_MOTIVO_TRASLADO, MODULO_MANTENIMIENTO_NIVEL,
        MODULO_MANTENIMIENTO_NUMERO_ESTABLECIMIENTO, MODULO_MANTENIMIENTO_NUMERO_EXPEDICION,
        MODULO_MANTENIMIENTO_PRODUCTO, MODULO_MANTENIMIENTO_PROVEEDOR, MODULO_MANTENIMIENTO_SUCURSAL,
        MODULO_MANTENIMIENTO_TIPO_DOCUMENTO, MODULO_MANTENIMIENTO_TIPO_VENTA,
        MODULO_MANTENIMIENTO_TIPO_PRODUCTO, MODULO_MANTENIMIENTO_TIMBRADO, MODULO_MANTENIMIENTO_USUARIO],


    8: [MODULO_PEDIDOS, MODULO_PRESUPUESTO, MODULO_ORDENES_DE_COMPRA,
        MODULO_COMPRAS, MODULO_NCC, MODULO_NDC, MODULO_NRC, MODULO_LIBROCOMPRAS, MODULO_PRODUCCION_ORDEN_COMPRA_LOTE,
        MODULO_PRODUCCION_COMPRA_LORE, MODULO_PRODUCCION_URBANIZACION,
        MODULO_PRODUCCION_PRECIO, MODULO_PRODUCCION_CONTRATO, MODULO_PRODUCCION_RESCISION,
        MODULO_PRODUCCION_CESION, MODULO_APERTURA_CAJA, MODULO_CIERRE_CAJA, MODULO_VENTA,
        MODULO_COBRANZA, MODULO_NRV, MODULO_NCV, MODULO_NDV,
        MODULO_ARQUEO, MODULO_LIBRO_VENTA, MODULO_MANTENIMIENTO_BARRIO, MODULO_MANTENIMIENTO_CAJA, MODULO_MANTENIMIENTO_CATEGORIA,
        MODULO_MANTENIMIENTO_CIUDAD, MODULO_MANTENIMIENTO_CLIENTE, MODULO_MANTENIMIENTO_EFECTIVO,
        MODULO_MANTENIMIENTO_FORMA_COBRO, MODULO_MANTENIMIENTO_FUNCIONARIO, MODULO_MANTENIMIENTO_IVA,
        MODULO_MANTENIMIENTO_MANZANA, MODULO_MANTENIMIENTO_MARCA, MODULO_MANTENIMIENTO_MONEDA,
        MODULO_MANTENIMIENTO_MOTIVO_CESION, MODULO_MANTENIMIENTO_MOTIVO_RESCISION,
        MODULO_MANTENIMIENTO_MOTIVO_TRASLADO, MODULO_MANTENIMIENTO_NIVEL,
        MODULO_MANTENIMIENTO_NUMERO_ESTABLECIMIENTO, MODULO_MANTENIMIENTO_NUMERO_EXPEDICION,
        MODULO_MANTENIMIENTO_PRODUCTO, MODULO_MANTENIMIENTO_PROVEEDOR, MODULO_MANTENIMIENTO_SUCURSAL,
        MODULO_MANTENIMIENTO_TIPO_DOCUMENTO, MODULO_MANTENIMIENTO_TIPO_VENTA,
        MODULO_MANTENIMIENTO_TIPO_PRODUCTO, MODULO_MANTENIMIENTO_TIMBRADO, MODULO_MANTENIMIENTO_USUARIO,
        MODULO_MANTENIMIENTO_COPIA_SEGURIDAD, MODULO_INFORMES_PEDIDO,
        MODULO_INFORMES_ORDEN_COMPRA, MODULO_INFORMES_PRESUPUESTO, MODULO_INFORMES_COMPRA, MODULO_INFORMES_NOTA_CREDITO_COMPRA,
        MODULO_INFORMES_PEDIDO, MODULO_INFORMES_ORDEN_COMPRA,
        MODULO_INFORMES_PRESUPUESTO, MODULO_INFORMES_COMPRA,
        MODULO_INFORMES_NOTA_CREDITO_COMPRA, MODULO_INFORMES_NOTA_DEBITO_COMPRA,
        MODULO_INFORMES_NOTA_REMISION_COMPRA, MODULO_INFORMES_BARRIO, MODULO_INFORMES_CAJA, MODULO_INFORMES_CIUDAD,
        MODULO_INFORMES_CATEGORIA, MODULO_INFORMES_CLIENTE, MODULO_INFORMES_EFECTIVO, MODULO_INFORMES_FORMA_COBRO,
        MODULO_INFORMES_FUNCIONARIO, MODULO_INFORMES_IVA, MODULO_INFORMES_MANZANA, MODULO_INFORMES_MARCA,
        MODULO_INFORMES_MONEDA, MODULO_INFORMES_MOTIVO_CESION, MODULO_INFORMES_MOTIVO_RESCISION,
        MODULO_INFORMES_MOTIVO_TRASLADO, MODULO_INFORMES_NIVEL, MODULO_INFORMES_NUMERO_ESTABLECIMIENTO,
        MODULO_INFORMES_NUMERO_EXPEDICION, MODULO_INFORMES_PRODUCTO, MODULO_INFORMES_PROVEEDOR,
        MODULO_INFORMES_SUCURSAL, MODULO_INFORMES_TIPO_DOCUMENTO, MODULO_INFORMES_TIPO_VENTA,
        MODULO_INFORMES_TIPO_PRODUCTO, MODULO_INFORMES_TIMBRADO, MODULO_INFORMES_USUARIO, MODULO_INFORMES_ORDEN_COMPRA_LOTE,
        MODULO_INFORMES_COMPRA_LOTE, MODULO_INFORMES_URBANIZACION, MODULO_INFORMES_CONTRATO, MODULO_INFORMES_VENTA,
        MODULO_INFORMES_NOTA_CREDITO_VENTA, MODULO_INFORMES_NOTA_DEBITO_VENTA, MODULO_INFORMES_NOTA_REMISION_VENTA,MODULO_INFORMES_CATEGORIA],

    



}

export { PERMISO_POR_NIVEL }